/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 phone.gltf --transform
Author: k. (https://sketchfab.com/k_nelms)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-mobile-phone-4ff99cf17b164e7b9790638c5d2ef4ce
Title: Low Poly Mobile Phone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/phone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, 0]}>
        <group rotation={[0.8, 0, 0]} scale={0.01}>
          <group position={[0, 43.98, 0]} rotation={[Math.PI / 4, 0, 0]}>
            <mesh geometry={nodes.Phone_Case_PhoneCase_Mat_0.geometry} material={materials.PhoneCase_Mat} />
            <mesh geometry={nodes.Phone_Case_PhoneFace_Mat_0.geometry} material={materials.PhoneFace_Mat} />
          </group>
          <mesh geometry={nodes.Phone_Camera_PhoneCase_Mat_0.geometry} material={materials.PhoneCase_Mat} position={[8.42, 57.72, -17.88]} rotation={[Math.PI / 4, 0, 0]} scale={[0.89, 1, 1]} />
          <mesh geometry={nodes.Power_Button_PhoneButton_Mat_0.geometry} material={materials.PhoneButton_Mat} position={[15.24, 54.69, -10.45]} rotation={[Math.PI / 4, 0, 0]} scale={[1, 1, 1.24]} />
          <mesh geometry={nodes.Volume_Up_PhoneButton_Mat_0.geometry} material={materials.PhoneButton_Mat} position={[-15.12, 54.49, -10.66]} rotation={[0.79, 0, -3.05]} scale={[1, 1, 0.79]} />
          <mesh geometry={nodes.Volume_Down_PhoneButton_Mat_0.geometry} material={materials.PhoneButton_Mat} position={[-15.12, 51.12, -7.3]} rotation={[0.79, 0, -3.05]} scale={[1, 1, 0.79]} />
          <mesh geometry={nodes.Camera_1_PhoneFace_Mat_0.geometry} material={materials.PhoneFace_Mat} position={[9.74, 58.84, -20.06]} rotation={[Math.PI / 4, 0, 0]} scale={1.7} />
          <mesh geometry={nodes.Camera_2_PhoneFace_Mat_0.geometry} material={materials.PhoneFace_Mat} position={[9.74, 55.58, -16.8]} rotation={[Math.PI / 4, 0, 0]} scale={1.7} />
          <mesh geometry={nodes.Camera_Light_Camera_Light1_0.geometry} material={materials.Camera_Light1} position={[6.83, 57.23, -18.45]} rotation={[Math.PI / 4, 0, 0]} scale={0.87} />
          <mesh geometry={nodes.Camera_Front_PhoneButton_Mat_0.geometry} material={materials.PhoneButton_Mat} position={[-0.42, 66.19, -18.69]} rotation={[Math.PI / 4, 0, 0]} scale={0.58} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/phone-transformed.glb')
